### PR TITLE
Add IInstrumentationContext interface

### PR DESCRIPTION
**Pull request by lucaslorentz**
@ffMathy

Creating an interface for InstrumentationContext. This would allow you to implement your own checks to determine if a method should be instrumented as source or as test.

Fixes https://github.com/lucaslorentz/minicover/issues/137

### CODE REVIEW

**Review by ffMathy — APPROVED** [review]
Once again, amazing work!

So clean and beautiful.

The only thing is booleans. I generally prefer enum results, because they are more readable. But it might be overkill.

**Comment by lucaslorentz** [comment]
That's true.
I will try to improve it later

**Comment by ffMathy** [comment]
Sounds great!

**Comment by lucaslorentz** [comment]
@ffMathy
Going to merge it, do you need a new package to be able to use the new code?

**Comment by ffMathy** [comment]
A new version of the nuget package would be great, yes 😊🙏

**Comment by lucaslorentz** [comment]
Done: https://github.com/lucaslorentz/minicover/releases/tag/v3.4.1
If [build](https://dev.azure.com/lucaslorentzlara/lucaslorentzlara/_build/results?buildId=606&view=results) passes the package will be there in a few minutes.

**Comment by ffMathy** [comment]
Great!

Also, did you see my question in the closed issue? The one about connecting?

**Comment by lucaslorentz** [comment]
Yes, just replied that

**Pull request merged**
