### PR TITLE
Add try finally to save even when an exception is thrown

### PR DESCRIPTION
**Pull request by bhugot**

### CODE REVIEW

**Comment by bhugot** [comment]
I still want to cleanup Instrumenter and tests full instrumentation

**Comment by lucaslorentz** [comment]
Just a comment.
Even if there is already a Try Finally wrapping the whole content of the method, you need to wrap again on another Try Finally.
Just adding more instructions to the existing Try Finally isn't enough because the existing finally instructions might throw exception.

Ex:
```
try {
  var methodContext = HitService.EnterMethod();
  ...original content
}
finally {
  ..original finally
  methodContext.Exit();
}
```
That isn't enough to ensure methodContext.Exit will always be called.

**Comment by bhugot** [comment]
I did consider that. it's in the test and it's more like that
```csharp
var methodContext = HitService.EnterMethod();
try {
    try {
    ...original content
  }
  finally {
    ..original finally
  }
}
finally {
  methodContext.Exit();
}
```
as we want to have access to methodContext
there is an even harder one with constructor

if you have this:

```csharp
private int afield = 10;

ctor()
 try {
    ...original content
  }
  finally {
    ..original finally
  }

```
Then as we have in il of the constructor something like that

```csharp
private int afield = 10;

ctor(){
afield = 10
base::ctor
 try {
    ...original content
  }
  finally {
    ..original finally
  }
}
```
As we can't encapsulate the base::ctor
I dit that
```csharp
ctor(){
var methodContext = HitService.EnterMethod();
try{
afield = 10
}
catch Exception{
methodContext.Exit();
throw;
}
base::ctor
try {
    try {
    ...original content
  }
  finally {
    ..original finally
  }
}
finally {
  methodContext.Exit();
}
```

**Comment by lucaslorentz** [comment]
Sounds good.
Why not doing a finally on fields initialization? Instead of catch throw

**Comment by bhugot** [comment]
because it will call exit even if we didn t left.

**Comment by lucaslorentz** [comment]
Yes. Of course 😄

**Comment by bhugot** [comment]
@lucaslorentz what are you waiting on this PR?

**Comment by lucaslorentz** [comment]
I was hoping to review it again.
But LGTM from my initial review.
It's hard to keep up your pace.

**Pull request merged**
