### PR TITLE
Remove try finally.

### PR DESCRIPTION
**Pull request by bhugot**
It s generating more problem than solving.
We should fix the problem with exception throwing by doing a low instrumentation of test methods

### CODE REVIEW

**Comment by bhugot** [comment]
@lucaslorentz I think that's the best move to do for now.

**Comment by lucaslorentz** [comment]
Makes sense.

**Comment by bhugot** [comment]
what do you think of this?
We detect tests projects and add another attribute on them and we set try finally in tests only.

**Comment by lucaslorentz** [comment]
That would require to always instrument test projects. I don't like to force that.
Maybe we can go back to `AppDomain.ProcessExit`.
It seems that .NET gives about 2 seconds to each listener attached to ProcessExit. If each TestMethod add a listener to ProcessExit,we would not face issues because each one writes it's content much faster than 2 seconds.

Another option would be to do the server to receive the hits.

**Comment by bhugot** [comment]
Instrument tests doesn t mean doing the code coverage on them

**Comment by bhugot** [comment]
The main problem is constructor and we don t need to instrument them

**Comment by bhugot** [comment]
While I m working on this process runing feature I think the problem is still the same. As we are caching the  test method if we don't call the exit method (the reason for the try finally) then we can't cache the test method.

**Comment by lucaslorentz** [comment]
If you're talking about the separate server that receives the hits.
I was thinking about sending all hit instructions in real time to it. Something like TestMethod+InstructionId.
So, we can still cache test method, but we would not wait the test method finish to send the hit instructions.
And that server would be responsible for aggregating hits to produce a small hits file.
But I'm not sure if we should go down that path.

**Comment by lucaslorentz** [comment]
Created an issue for that: https://github.com/lucaslorentz/minicover/issues/83
Please, let's brainstorm it there.

**Pull request merged**
