### PR TITLE
Assembly resolve failure

### PR DESCRIPTION
**Pull request by baor**
Hey @lucaslorentz,
I faced with situation when DefaultAssemblyResolver was not able to resolve a dependency on linux machine.

I am not sure why it happened. It was not able to find a dll in nuget packages.
So I did a minor refactoring to reuse GetFiles method to manually search for dll in work folder.
It looked like it helped.

### CODE REVIEW

**Comment by baor** [comment]
It looks like it might be related to  #43

**Comment by lucaslorentz** [comment]
Thanks @baor 

Can you please describe the path where the dll in nuget package is found?

Instead of searching through all directories, I would prefer to use information from `deps.json` and `runtimeconfig.dev.json` to pinpoint the exact location and version of the assembly. Do you have those files in your build outpout (bin) folder?

**Comment by lucaslorentz** [comment]
I wrote an AssemblyLoader some time ago that uses deps.json file to locate dlls, but it is not written for Mono.Cecil. It worked well for .NET Core assembly loaders, maybe we can do something similar for Mono.Cecil.

```
        public class AssemblyLoader : AssemblyLoadContext
        {
            private DependencyContext _dependencyContext;
            private List<string> _probingPaths;

            public AssemblyLoader(string assemblyPath)
            {
                var assemblyDirectory = Path.GetDirectoryName(assemblyPath);

                var depsJsonPath = Path.ChangeExtension(assemblyPath, "deps.json");
                if (File.Exists(depsJsonPath))
                {
                    using (var depsJsonStream = File.OpenRead(depsJsonPath))
                    {
                        using (var reader = new DependencyContextJsonReader())
                        {
                            _dependencyContext = reader.Read(depsJsonStream);
                        }
                    }
                }

                _probingPaths = new List<string>
                {
                    assemblyDirectory
                };

                var runtimeConfigPath = Path.ChangeExtension(assemblyPath, "runtimeconfig.dev.json");
                if (File.Exists(runtimeConfigPath))
                {
                    var runtimeConfigContent = File.ReadAllText(runtimeConfigPath);
                    var runtimeConfig = JsonConvert.DeserializeObject<JObject>(runtimeConfigContent);

                    var additionalProbingPaths = runtimeConfig["runtimeOptions"]?["additionalProbingPaths"];
                    if (additionalProbingPaths != null)
                    {
                        foreach (var path in additionalProbingPaths.Values<string>())
                        {
                            if (!path.Contains("|"))
                            {
                                _probingPaths.Add(path);
                            }
                        }
                    }
                }
            }

            protected override Assembly Load(AssemblyName assemblyName)
            {
                if (_dependencyContext != null)
                {
                    var dep = _dependencyContext.CompileLibraries.FirstOrDefault(c =>
                    {
                        return c.Name == assemblyName.Name;
                    });

                    if (dep != null)
                    {
                        foreach (var ass in dep.Assemblies)
                        {
                            foreach (var p in _probingPaths)
                            {
                                var t = Path.Combine(new[] { p, dep.Path, ass }.Where(x => x != null).ToArray());
                                if (File.Exists(t))
                                {
                                    return LoadFromAssemblyPath(t);
                                }
                            }
                        }
                    }
                }

                return null;
            }
        }
```

**Comment by baor** [comment]
Thank you for the response, Lucas!

The exception is below
`Instrumenting assembly "MainService"

Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve a
ssembly: 'Logging, Version=2.1.3.0, Culture=neutral, PublicKeyToken=
null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, Reader
Parameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Ob
ject constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeRefere
nce type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefiniti
on parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder,
 MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBui
lder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream
, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1
stream, WriterParameters parameters)
   at MiniCover.Instrumentation.Instrumenter.InstrumentAssemblyIfNecessary(Strin
g assemblyFile)
   at MiniCover.Instrumentation.Instrumenter.VisitAssemblyGroup(IEnumerable`1 as
semblyFiles)
   at MiniCover.Instrumentation.Instrumenter.Execute()
   at MiniCover.Program.<>c__DisplayClass0_1.<Main>b__8()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(Strin
g[] args)
   at MiniCover.Program.Main(String[] args)`

Default resolver check folders:
`
.
bin
<bin/Release>
`

The Logging.dll is a part of nuget package at
`
 .nuget/packages
`

So my change add work folder and results in adding a search directory like
`
 ./.nuget/packages/logging/2.1.3/lib/netstandard1.3
`

**Comment by baor** [comment]
Related to deps.json, I see the file in <bin/Release>, but it doesn't point to folder with packages by some reason. I mean, all paths look like
```
 "runtime": {
   "lib/netstandard1.3/Microsoft.CodeAnalysis.CSharp.dll": {}
 }
```

**Comment by baor** [comment]
but in <obj> folder I see a file like **MainService.csproj.nuget.g.props** with full path to .nuget/packages

**Comment by lucaslorentz** [comment]
Do you also have files like *.runtimeconfig.dev.json inside the test projects bin?

**Comment by baor** [comment]
> Do you also have files like *.runtimeconfig.dev.json inside the test projects bin?

All UnitTests project have this file, IntegrationTest project and WebService project.

**Comment by baor** [comment]
> I wrote an AssemblyLoader some time ago that uses deps.json file to locate dlls..

I partially used this code to create **CustomAssemblyResolver**. The idea is to override SearchDirectory to do search in subfolders.

Not sure about implementing AssemblyResolver from scratch, because of possible cross-platform issues

**Comment by lucaslorentz** [comment]
Hey @baor 
I created a PR with my suggested changes:
https://github.com/Travix-International/minicover/pull/3/files

Once you merge it this PR will also be updated and then I can merge it.

Basically, I implemented 2 suggestions that I had:
- Not use GetFiles, because you don't really need glob patterns. You can use Directory.GetFiles, it also supports recursive searching.
- Instead of doing a very wide search for assembly dll, let's try using the `deps.json` file to narrow down the exact assembly we need to load. If that works I think it's safer than searching recursively inside nuget packages folder.

**Comment by lucaslorentz** [comment]
@baor 
Is it working well? Can I merge the PR?

**Comment by baor** [comment]
hey @lucaslorentz 
Sorry, just was able to test it....and it doesn't work. I will try to investigate and will come up with update

**Comment by baor** [comment]
I've updated this branch:
https://github.com/Travix-International/minicover/pull/5

**Pull request merged**
