### PR TITLE
Optimize reports

### PR DESCRIPTION
**Pull request by lucaslorentz**
Performance improvements suggested on: https://github.com/lucaslorentz/minicover/issues/13

@exyi, I didn't notice performance improvement cause there are very basic tests in this repository.

Please, let me know if that's what you suggested.

### CODE REVIEW

**Comment by exyi** [comment]
Thanks a lot, it still isn't exactly fast but it work well.

**Comment by lucaslorentz** [comment]
Well, I guess we need to do more optimizations. 😄

**Comment by lucaslorentz** [comment]
I will leave https://github.com/lucaslorentz/minicover/issues/13 open so we can optimize more.

**Comment by lucaslorentz** [comment]
Covered by https://github.com/lucaslorentz/minicover/pull/16

**Pull request merged**
