### PR TITLE
Hits now has a count and a fast mode: save at the end.

### PR DESCRIPTION
**Pull request by havocbcn**
Good night, 

This is a big step, I will understand if you have some concers to merge it.

Two ideas
- The hit file will have the id and number of repetitions, this decrease heavily the hit file size (in my case from >400Mb to few Kb)
- Save the hit file when has to be save (just at the end).

and when is saved?

Two possibilities:
- slow: source indicated by parameters cover everything, so instrumenter will be like Init - Hit - Hit... in this case, nothing changes, every hit is saved in each hit call.
- fast: source indicated by parameters cover some dlls, other's aren't covered (the test dll or third party), so instrumenter will mark with 'hit' the sources dll's, and with 'end' the others. Now the test will be Init - End - Hit - Hit - hit... End, so in the End will be a save, in hits just recorded in a dictionary. Even in throw scenarios will work (because the test always will assert).

Some boolean has to be used to control when a fast or slow control we are (the build.sh is in slow, but my project is in fast.
I have a /src folder and a /test  folder at the same level, so my unit testing are outside.

sonarqube continue working with that, and the build.sh exactly the same.

PD: the issue about instrument outside dll's, as I explain, are used here!
PD2: using the stacktrace works but is slow.

### CODE REVIEW

**Comment by bhugot** [comment]
You can do it an easier way.

just by puting your count increment and saving at the processExxit.

```csharp
static HitService()
        {
            AppDomain.CurrentDomain.ProcessExit += (sender, args) => Save();
        }
```

The problem I see with your implementation is that we can't by example trace the more information if wanted like all the tests that are hitting. I think we should introduce a way to provide how we fill the hit file and then read it for report also.

It should be quiet easy to do that. I did same work on my branch 
Going to try to fix allow multiple configuration

**Comment by bhugot** [comment]
I did the implementation if you could try the perf on your big solution

**Comment by bhugot** [comment]
I have one more thing to fix because your are going to have one line by tests execution

**Comment by havocbcn** [comment]
I didnt't know about ProcessExit.exit, but as I imagine has some problems: https://blogs.msdn.microsoft.com/jmstall/2006/11/26/appdomain-processexit-is-not-guaranteed-to-be-called/

I suppose that covering test, an exception has to be catched, so your implementation is cleaner.

The problem that you said that I only  save id code - count, It's only because I didn't try to change the hit file functionality, just speeding up things, I prefer to do a merge for one functionality at a time, the refactor of the hit file it's not important for me now.

I will try you branch (until friday I will have no free time), your code are simplier

PD: my project is quite simple but very recursive, more than 20.000 executions some parts, so the hit file is huge compared the size of the code)

**Comment by bhugot** [comment]
I asked my self about process exception but it would mean the tests runner himself failed and in that case I don t think we care about the hitfile.

**Pull request closed without merging**
