### PR TITLE
Coveralls improvements

### PR DESCRIPTION
**Pull request by lucaslorentz**
This PR improves coveralls on top of @aseduto PR: https://github.com/lucaslorentz/minicover/pull/72

@aseduto @bhugot Can you please review and maybe test it locally?

You can either specify a known `service-name` and `service-job-id`, and coveralls will get all information from travis-ci for instance.

Or you can specify `repo-token` + all git information like `branch`, `commit`, `commit-message`...

### CODE REVIEW

**Comment by lucaslorentz** [comment]
I will add unit tests before merging this PR.

**Comment by aseduto** [comment]
Hi @lucas,
I have created a small test repo here: https://github.com/aseduto/testman/tree/master

Unfortunately as you can see here https://coveralls.io/builds/16222589/source?filename=Program.cs  line 24 is marked as not called (correctly) however lines  13 and 14 are marked as called incorrectly since line 24 is not called.

Looking at the same execution with mine pr everything is correct: https://coveralls.io/builds/16222353/source?filename=Program.cs

You can look at the builds here:
https://ci.appveyor.com/project/aseduto/testman/build/0.0.6 (my pr)
https://ci.appveyor.com/project/aseduto/testman/build/0.0.11 (yours)

As far as I understand, and this is how I have correct in the my pr, you have instruction witch covers more lines and you have to take that into considerations when computing coverage as I did.

**Comment by lucaslorentz** [comment]
Thanks @aseduto for testing it.

Now I see your logic to handle that.
https://github.com/lucaslorentz/minicover/pull/76/commits/8828111324c2091711446d54c7ceadcd072bce6e#diff-edcaa1f1eb366da1e9902a66a153613cR230

We have that same issue on other reports, I will add your logic back and also fix other reports.

Btw:
I removed your warning about duplicated instructions because that's actually normal. Lines like: `for (let i = 0; i < x; i++)` have multiple instructions.

**Comment by aseduto** [comment]
[coverage.zip](https://github.com/lucaslorentz/minicover/files/1859713/coverage.zip)
Hi @lucaslorentz,

Great.

I just add the warning since I had noticed that you have duplicated instructions.
In the attached file from the same run as before instruction 11 and 13 as well as  12 and 14 seems to be duplicated.

I suspected this is due to the fact that in the GetAllMethods extension for AssemblyDefinition you loop for all types, and that should alredy contains all NestedTypes. Than in the GetAllMethods extension for TypeDefinition you once again process NestedTypes.

**Comment by lucaslorentz** [comment]
@aseduto 
I'm going to fix the coverage of lambda on another PR.
Because it affects all reports, I'm working on a solution.

**Pull request merged**
